# Generated by Django 4.2.2 on 2023-06-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='sell_price',
            field=models.CharField(default='0.00', max_length=255),
        ),
    ]
